name: check_connectivity_with_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
